name: xplane_connect
description: Library to get an easy stream of data about XPlane UDP protocol.
version: 1.0.1-dev.1
homepage: https://github.com/Lulzphantom/XPlane-DataOutputReceiver-Dart/

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  udp: ^5.0.3

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.21.1
